required_plugins = %w(virtualbox_WSL2)

plugins_to_install = required_plugins.select { |plugin| not Vagrant.has_plugin? plugin }
if not plugins_to_install.empty?
  puts "Installing plugins: #{plugins_to_install.join(' ')}"
  if system "vagrant plugin install #{plugins_to_install.join(' ')}"
    exec "vagrant #{ARGV.join(' ')}"
  else
    abort "Installation of one or more plugins has failed. Aborting."
  end
end

Vagrant.configure("2") do |config|
    config.vm.define "main" do |subconfig|
        subconfig.vm.box = "generic/ubuntu2310"
        subconfig.vm.hostname = "main"
        subconfig.vm.network "public_network", bridge: "BRIDGE"
    end

    config.vm.synced_folder "..", "/bootstrap", type: "rsync",
    rsync__exclude: ["venv", ".git", ".idea", "vm/vagrant", "vm/packer_cache", "*.box"]
end