- name: Install VSCode
  block:
    - name: Add gpg public key
      ansible.builtin.get_url:
        url: "https://packages.microsoft.com/keys/microsoft.asc"
        dest: "/tmp/vscode_temp_key"
        mode: "0644"
    - name: Add repository to sources list # noqa risky-shell-pipe
      ansible.builtin.shell: |
        cat /tmp/vscode_temp_key | gpg --dearmor > packages.microsoft.gpg
        sudo install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
        echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" \
          | sudo tee /etc/apt/sources.list.d/vscode.list > /dev/null
        rm -f packages.microsoft.gpg
      become: true
      changed_when: false
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      become: true
    - name: Install VSCode package
      ansible.builtin.apt:
        name: code
        state: present
      become: true
