- name: Install Lens
  block:
    - name: Add repository to sources list # noqa risky-shell-pipe command-instead-of-module
      ansible.builtin.shell: |
        curl -fsSL https://downloads.k8slens.dev/keys/gpg \
         | gpg --dearmor | sudo tee /usr/share/keyrings/lens-archive-keyring.gpg > /dev/null
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/lens-archive-keyring.gpg] https://downloads.k8slens.dev/apt/debian stable main" \
         | sudo tee /etc/apt/sources.list.d/lens.list > /dev/null
      become: true
      changed_when: false
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      become: true
    - name: Install Lens package
      ansible.builtin.apt:
        name: lens
        state: present
      become: true
