- name: Install mise
  block:
    - name: Add repository to sources list # noqa risky-shell-pipe
      ansible.builtin.shell:
        cmd: curl -fsSL https://mise.jdx.dev/gpg-key.pub | gpg -o /etc/apt/keyrings/mise-archive-keyring.gpg --yes --dearmor
        creates: /etc/apt/keyrings/mise-archive-keyring.gpg
      become: true

    - name: Add apt repository
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/etc/apt/keyrings/mise-archive-keyring.gpg arch=amd64] https://mise.jdx.dev/deb stable main
        filename: mise
        update_cache: true
        state: present
      become: true

    - name: Install mise package
      ansible.builtin.apt:
        name: mise
        state: present
      become: true

- name: Update .zshrc file
  when: mise_edit_rc_file
  ansible.builtin.lineinfile:
    path: "{{ home }}/.zshrc"
    line: plugins+=(mise)
    insertbefore: 'source \$ZSH\/oh-my-zsh\.sh'
    state: present

- name: Install mise plugins
  changed_when: false
  loop: "{{ mise_plugins }}"
  ignore_errors: true
  register: mise_plugin_errors
  ansible.builtin.command: mise use -g {{ item }} -y

- name: "Print mise errors"
  ansible.builtin.debug:
    msg: "Errors: {{ mise_plugin_errors }}"

- name: Add extra line in .zshrc file
  when: mise_edit_rc_file and mise_line_in_file
  loop: "{{ mise_line_in_file }}"
  ansible.builtin.lineinfile:
    path: "{{ home }}/.zshrc"
    line: "{{ item }}"
    state: present
