- name: Download repo key
  ansible.builtin.shell:
    cmd: curl -sSL https://packagecloud.io/slacktechnologies/slack/gpgkey | gpg --dearmor --output /usr/share/keyrings/slack-archive-keyring.gpg
    creates: /usr/share/keyrings/slack-archive-keyring.gpg
  become: true

- name: Add apt repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/slack-archive-keyring.gpg] https://packagecloud.io/slacktechnologies/slack/debian/ jessie main
    filename: slack
    update_cache: true
    state: present
  become: true

- name: Install required packages
  ansible.builtin.apt:
    name: "slack-desktop"
    state: present
  become: true
