- name: Install Docker
  block:
    - name: Add repository to sources list # noqa risky-shell-pipe command-instead-of-module
      ansible.builtin.shell:
        cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg -o /etc/apt/keyrings/docker.gpg --dearmor --yes
        creates: /etc/apt/keyrings/docker.gpg
      become: true

    - name: Add apt repository
      ansible.builtin.apt_repository:
        repo: deb [ arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg ] https://download.docker.com/linux/ubuntu jammy stable
        filename: docker
        update_cache: true
        state: present
      become: true

    - name: Install docker packages
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
      become: true

- name: "Create Docker group"
  become: true
  ansible.builtin.group:
    name: "docker"
    state: "present"

- name: "Add user to Docker group"
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    groups: "docker"
    append: true
