- name: "Install git, curl and other essential packages"
  become: true
  ansible.builtin.apt:
    pkg:
      - "git"
      - "curl"
      - "wget"
      - "coreutils"
      - "ca-certificates"
      - "build-essential"
      - "apt-transport-https"
      - "software-properties-common"
